name: Renovate

on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v42.0.3
      with:
        configurationFile: ./.github/renovate-config.js
        token: ${{ secrets.RENOVATE_TOKEN }}
      env:
        LOG_LEVEL: 'debug'